CREATE TABLE TB_M_ROLE(
	ID [UNIQUEIDENTIFIER] NOT NULL DEFAULT NEWID(),
	NAME VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(200) NOT NULL,
	PRIMARY KEY (ID)
);

INSERT INTO TB_M_ROLE VALUES(NEWID(), 'Admin', 'administrator');
INSERT INTO TB_M_ROLE VALUES(NEWID(), 'Member', 'member');