CREATE TABLE PRODUCT21(
	ID [UNIQUEIDENTIFIER] NOT NULL DEFAULT NEWID(),
	CODE VARCHAR(20) NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	DESCRIPTION VARCHAR(100) NOT NULL,
	PRICE DECIMAL NOT NULL,
	STOK INT NOT NULL,
	PRIMARY KEY (ID)
);

INSERT INTO PRODUCT21 VALUES (NEWID(), 'BA', 'Baju Anak', 'desc', 50000, 10);
INSERT INTO PRODUCT21 VALUES (NEWID(), 'BR', 'Baju Remaja', 'desc', 70000, 30);
INSERT INTO PRODUCT21 VALUES (NEWID(), 'BD', 'Baju Dewasa', 'desc', 80000, 20);
INSERT INTO PRODUCT21 VALUES (NEWID(), 'BW', 'Baju Wanita', 'desc', 40000, 120);
INSERT INTO PRODUCT21 VALUES (NEWID(), 'BP', 'Baju Pria', 'desc', 90000, 10);

CREATE TABLE PRODUCT21_DETAIL(
	ID [UNIQUEIDENTIFIER] NOT NULL DEFAULT NEWID(),
	CODE VARCHAR(20) NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	SUPPLIER_NAME VARCHAR(20) NOT NULL,
	SUPPLIER_CODE VARCHAR(20) NOT NULL,
	BEST_SELLER VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID)
);
INSERT INTO PRODUCT21_DETAIL VALUES (NEWID(), 'BA', 'Baju Anak', 'anton', 'ant', 'budi');
INSERT INTO PRODUCT21_DETAIL VALUES (NEWID(), 'BR', 'Baju Remaja', 'budi1', 'budi1', 'budi1');
INSERT INTO PRODUCT21_DETAIL VALUES (NEWID(), 'BR', 'Baju Remaja', 'budi2', 'budi2', 'budi2');
INSERT INTO PRODUCT21_DETAIL VALUES (NEWID(), 'BR', 'Baju Remaja', 'budi3', 'budi3', 'budi3');

-- LEFT JOIN TOP 1
SELECT * 
FROM PRODUCT21 A
LEFT JOIN 
	(SELECT *, row_number() over (partition by lower(CODE), lower(NAME) order by NAME) as rn FROM PRODUCT21_DETAIL) B 
ON A.CODE = B.CODE AND A.NAME = B.NAME AND  B.rn = 1
ORDER BY A.CODE;
