CREATE TABLE TB_M_PRODUCT_CATEGORY(
	ID [UNIQUEIDENTIFIER] NOT NULL PRIMARY KEY DEFAULT NEWID(),
	NAME VARCHAR(20) NOT NULL
);

INSERT INTO TB_M_PRODUCT_CATEGORY VALUES(NEWID(), 'MAN');
INSERT INTO TB_M_PRODUCT_CATEGORY(NAME) VALUES('WOMEN');
INSERT INTO TB_M_PRODUCT_CATEGORY VALUES('6aec42bf-d4b1-4b47-b71f-a82bb7cab153', 'KIDS');

SELECT * FROM TB_M_PRODUCT_CATEGORY;