CREATE OR ALTER PROCEDURE USP_UPD_MODULE_FUNCTION
@BY VARCHAR(50),
@DATA VARCHAR(MAX)
AS
BEGIN
	DECLARE @NOW DATETIME = GETDATE()
	DECLARE @TEMP TABLE(
		NAME VARCHAR(50) NOT NULL,
		VALUE VARCHAR(50) NOT NULL,
		MODULE VARCHAR(50) NOT NULL,
		[FUNCTION] VARCHAR(50) NOT NULL
	)

	INSERT INTO @TEMP(NAME, VALUE, MODULE, [FUNCTION])
	SELECT 
		JSON_Value (A.value, '$.Name'),
		JSON_Value (A.value, '$.Value'),
		JSON_Value (A.value, '$.Module'),
		JSON_Value (A.value, '$.Function')
	FROM OPENJSON(@DATA) AS A 

	DELETE TB_M_FUNCTION
	DELETE TB_M_MODULE
	INSERT INTO TB_M_MODULE
	SELECT 
		MODULE,
		MODULE,
		'',

		@NOW,
		@BY,
		NULL,
		''
	FROM @TEMP
	GROUP BY MODULE

	INSERT INTO TB_M_FUNCTION
	SELECT 
	[VALUE],
	MODULE,
	[FUNCTION],
	'',

	@NOW,
	@BY,
	NULL,
	''
	FROM @TEMP
END