DROP TABLE TB_M_MODULE;
CREATE TABLE TB_M_MODULE(
	ID VARCHAR(50) NOT NULL,
	NAME VARCHAR(50) NOT NULL UNIQUE,
	DESCRIPTION VARCHAR(200) NOT NULL,

	CREATED_AT DATETIME NOT NULL,
	CREATED_BY VARCHAR(50) NOT NULL,
	UPDATED_AT DATETIME NULL,
	UPDATED_BY VARCHAR(50) NOT NULL,
	
	PRIMARY KEY(ID)
);