DROP TABLE TB_M_FUNCTION;
CREATE TABLE TB_M_FUNCTION(
	ID VARCHAR(50) NOT NULL,
	MODULE_ID VARCHAR(50) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(200) NOT NULL,
	[ORDER] INT NOT NULL,

	CREATED_AT DATETIME NOT NULL,
	CREATED_BY VARCHAR(50) NOT NULL,
	UPDATED_AT DATETIME NULL,
	UPDATED_BY VARCHAR(50) NOT NULL,
	
	PRIMARY KEY(ID),
	CONSTRAINT FK_FUNCTION_MODULE FOREIGN KEY (MODULE_ID) REFERENCES TB_M_MODULE(ID)
);