CREATE OR ALTER PROCEDURE USP_UPD_MODULE_FUNCTION
@BY VARCHAR(50),
@DATA VARCHAR(MAX)
AS
BEGIN
	DECLARE @NOW DATETIME = GETDATE()
	DECLARE @TEMP TABLE(
		ID VARCHAR(50) NOT NULL,
		IDTEXT VARCHAR(50) NOT NULL,
		MODULE VARCHAR(50) NOT NULL,
		FUNCTION_NAME VARCHAR(50) NOT NULL,
		[ORDER] INT NOT NULL
	)

	INSERT INTO @TEMP(ID, IDTEXT, MODULE, FUNCTION_NAME, [ORDER])
	SELECT 
		JSON_Value (A.value, '$.Id'),
		JSON_Value (A.value, '$.IdText'),
		JSON_Value (A.value, '$.Module'),
		JSON_Value (A.value, '$.FunctionName'),
		JSON_Value (A.value, '$.Order')
	FROM OPENJSON(@DATA) AS A 

	DELETE TB_M_FUNCTION
	DELETE TB_M_MODULE
	INSERT INTO TB_M_MODULE
	SELECT 
		MODULE,
		MODULE,
		'',

		@NOW,
		@BY,
		NULL,
		''
	FROM @TEMP
	GROUP BY MODULE

	INSERT INTO TB_M_FUNCTION
	SELECT 
	[ID],
	MODULE,
	[FUNCTION_NAME],
	[IDTEXT],
	[ORDER],

	@NOW,
	@BY,
	NULL,
	''
	FROM @TEMP
END