DROP TABLE TB_M_USER_ROLE;
DROP TABLE TB_M_USER;
CREATE TABLE TB_M_USER(
	ID [UNIQUEIDENTIFIER] NOT NULL DEFAULT NEWID(),
	USERNAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	FULLNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	TELP1 VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(500) NULL,
	ISACTIVE BIT NOT NULL,
	PRIMARY KEY (ID)
);

INSERT INTO TB_M_USER VALUES(NEWID(), 'Admin', 'tegar.s@weefer.co.id', 'administrator', '123', '085123123123', '', 0);
INSERT INTO TB_M_USER VALUES(NEWID(), 'anto', 'anto@weefer.co.id', 'Anto Wijaya', '123', '0851098767823', '', 0);
INSERT INTO TB_M_USER VALUES(NEWID(), 'Toni', 'toni@weefer.co.id', 'Toni Wijaya', '123', '0850986671233', '', 0);
