DROP TABLE TB_M_USER_ROLE;
CREATE TABLE TB_M_USER_ROLE(
	ID [UNIQUEIDENTIFIER] NOT NULL DEFAULT NEWID(),
	USER_ID [UNIQUEIDENTIFIER] NOT NULL,
	ROLE_ID [UNIQUEIDENTIFIER] NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_USERROLE_USER FOREIGN KEY(USER_ID) REFERENCES TB_M_USER(ID),
	CONSTRAINT FK_USERROLE_ROLE FOREIGN KEY(ROLE_ID) REFERENCES TB_M_ROLE(ID)
);
