DROP TABLE TB_M_ROLE_FUNCTION;
CREATE TABLE TB_M_ROLE_FUNCTION(
	ID [UNIQUEIDENTIFIER] NOT NULL DEFAULT NEWID(),
	ROLE_ID [UNIQUEIDENTIFIER] NOT NULL,
	FUNCTION_ID VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_ROLEFUNCTION_ROLE FOREIGN KEY (ROLE_ID) REFERENCES TB_M_ROLE(ID)
);
